### ISSUE TITLE
Cannot install with composer

### ISSUE THREAD

**Issue by kwn** [ollieLtd/InstagramBundle#1]
During `composer update` I get an error. I'm using Symfony2 Standard Edition 2.5

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ollieltd/instagram-bundle dev-master@dev -> satisfiable by ollieltd/instagram-bundle[dev-master].
    - ollieltd/instagram-bundle dev-master requires instaphp/instaphp 2.* -> satisfiable by instaphp/instaphp[2.0.10, 2.0.6, 2.0.7, 2.0.8, 2.0.9].
    - instaphp/instaphp 2.0.10 requires monolog/monolog 1.8.* -> satisfiable by monolog/monolog[1.8.0].
    - instaphp/instaphp 2.0.6 requires monolog/monolog 1.8.* -> satisfiable by monolog/monolog[1.8.0].
    - instaphp/instaphp 2.0.7 requires monolog/monolog 1.8.* -> satisfiable by monolog/monolog[1.8.0].
    - instaphp/instaphp 2.0.8 requires monolog/monolog 1.8.* -> satisfiable by monolog/monolog[1.8.0].
    - instaphp/instaphp 2.0.9 requires monolog/monolog 1.8.* -> satisfiable by monolog/monolog[1.8.0].
    - Conclusion: don't install monolog/monolog 1.8.0
```

**Comment by kwn** [comment]
There's a conflict in Instaphp and Monolog. Symfony installs monolog 1.12.0, but Instaphp requires 1.8.0. The last version of Instaphp that allows to monolog 1.12 is 2.0.3.1-beta (actually this version doesn't need monolog at all). So due to stability settings InstagramBundle should ask for:

```
"instaphp/instaphp": "~2.0@beta"
```

I'll drop a message for Sesser to bump the monolog version requirement in Instaphp package.

**Comment by kwn** [comment]
Related to:

https://github.com/sesser/Instaphp/issues/31

**Comment by ollietb** [comment]
@kwn wow that was quick, I only pushed this repo yesterday :) I'm still working on fixing a few things, but yes the monolog requirement is the responsibility of @sesser

**Comment by kwn** [comment]
@ollietb Sesser fixed monolog version. Now everything works fine!
