### ISSUE TITLE
GuzzleHttp ConnectException

### ISSUE THREAD

**Issue by zabojad** [ollieLtd/InstagramBundle#12]
I regularly have those errors in production:

```
 [GuzzleHttp\Exception\ConnectException]
  cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received

  [GuzzleHttp\Ring\Exception\ConnectException]
  cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received
```

Any idea what could happen ?

**Comment by sigismund** [comment]
I have the same problem and I can't pinpoint any common points in these errors. Did you maybe already figure out the problem? 

What kind "stack" are you using on production?
I am using Ubuntu with Apache/2.4.7 + PHP 7.0.5-3+donate.sury.org~trusty.

**Comment by ollietb** [comment]
I think it's probably Instagram's servers being slow
