### ISSUE TITLE
Bad Request 

### ISSUE THREAD

**Issue by bornbygoogle** [ollieLtd/InstagramBundle#18]
Sr for disturbing, but I did exactly what you said in README.md, but when I try to get media of user, symfony 2.7.9 gave me this error ?

Could you tell me what is wrong ?

```
        case 400: //-- 400 error slipped through?
            throw new \Instaphp\Exceptions\HttpException($response->getReasonPhrase(), $response->getStatusCode(), $igresponse);
            break;
```

**Comment by jakenoble** [comment]
I have the same in Symfony3.1

**Comment by ollietb** [comment]
@bornbygoogle do you know what the error message from Instagram is?

**Comment by jakenoble** [comment]
I get Access Token missing

**Comment by bornbygoogle** [comment]
Sorry but can you tell me how can I find out the error message from Instagram ? I can log in with checkstatus, but I can't get media of user, apparement, my account is in sandbox ? Is that the problem ?

**Comment by ollietb** [comment]
@bornbygoogle what is the error message returned from Instagram in the exception `$response->getReasonPhrase()`?

**Comment by bornbygoogle** [comment]
```
      case 502:
        case 503:
        case 400: //-- 400 error slipped through?
            throw new \Instaphp\Exceptions\HttpException($response->getReasonPhrase(), $response->getStatusCode(), $igresponse);
            break;
        case 429:
            throw new \Instaphp\Exceptions\OAuthRateLimitException($igresponse->meta['error_message'], 429, $igresponse);
```

This is what I got ...

**Comment by bornbygoogle** [comment]
This is Stack Trace (Plain Text) :

[1] Instaphp\Exceptions\HttpException: Bad Request
    at n/a
        in /media/bornbygoogle/3474D74B0101E526/ProgWeb/persoworld/vendor/instaphp/instaphp/src/Instaphp/Instagram/Instagram.php line 364

```
at Instaphp\Instagram\Instagram->parseResponse(object(Response))
    in /media/bornbygoogle/3474D74B0101E526/ProgWeb/persoworld/vendor/instaphp/instaphp/src/Instaphp/Instagram/Instagram.php line 201

at Instaphp\Instagram\Instagram->get('/users/search', array('count' => '100', 'q' => 'snoopdogg'))
    in /media/bornbygoogle/3474D74B0101E526/ProgWeb/persoworld/vendor/instaphp/instaphp/src/Instaphp/Instagram/Users.php line 155

at Instaphp\Instagram\Users->Search('snoopdogg', array('count' => '100', 'q' => 'snoopdogg'))
    in /media/bornbygoogle/3474D74B0101E526/ProgWeb/persoworld/vendor/instaphp/instaphp/src/Instaphp/Instagram/Users.php line 88

at Instaphp\Instagram\Users->FindId('snoopdogg')
    in /media/bornbygoogle/3474D74B0101E526/ProgWeb/persoworld/src/persoworldBundle/Controller/PhotosController.php line 18

at persoworldBundle\Controller\PhotosController->indexAction()
    in  line 

at call_user_func_array(array(object(PhotosController), 'indexAction'), array())
    in /media/bornbygoogle/3474D74B0101E526/ProgWeb/persoworld/app/bootstrap.php.cache line 3160

at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), '1')
    in /media/bornbygoogle/3474D74B0101E526/ProgWeb/persoworld/app/bootstrap.php.cache line 3119

at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), '1', true)
    in /media/bornbygoogle/3474D74B0101E526/ProgWeb/persoworld/app/bootstrap.php.cache line 3273

at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Request), '1', true)
    in /media/bornbygoogle/3474D74B0101E526/ProgWeb/persoworld/app/bootstrap.php.cache line 2484

at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
    in /media/bornbygoogle/3474D74B0101E526/ProgWeb/persoworld/web/app_dev.php line 29

at require('/media/bornbygoogle/3474D74B0101E526/ProgWeb/persoworld/web/app_dev.php')
    in /media/bornbygoogle/3474D74B0101E526/ProgWeb/persoworld/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/config/router_dev.php line 40
```

**Comment by bornbygoogle** [comment]
You figured out where is the error ? :D

**Comment by bornbygoogle** [comment]
Any news for this error please ?

**Comment by baronvertigovongrahamthesecondofsealand** [comment]
Had this issue myself, turns out to be a problem with the docs. If you blindly copy/paste the yml config (which is fair), youll pull in... a php comment. This is then added to the access_token when its used in the Instagram requests, and the server complains.

Just search in your config.yml for: // (optional)

**Comment by bornbygoogle** [comment]
I can confirm that the error mentioned is not due to that ''// optional" ( because i deleted theses lines), the error is still there. 

Btw, can you tell me thoses parameters, i'll add them in config.yml ? or service.yml ? or parameters.yml ?

> Add these parameters: 
instagram_api_client_id: YOUR_API_ID
instagram_api_client_secret: YOUR_API_SECRET
instagram_api_access_token: YOUR_API_ACCESS_TOKEN // (optional)

**Comment by baronvertigovongrahamthesecondofsealand** [comment]
Sorry that didnt work for you, it did for me, and is a problem with the docs. Ive submitted a patch for it.

**Comment by ghost** [comment]
Same Error (Symfony 3.2.4) .. any news please ?

**Comment by nouchka** [comment]
@NicolasPion had same error in the same symfony version, was linked to issue #16 and symfony 3 compatibility. I forked and tried solution proposed by @mkeremkoc and it works. Hope it helps.

**Comment by TheFox** [comment]
#21 fixed the problem.
